name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    # Start by getting the version number we originally had
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - run: git checkout HEAD^
    - name: Get old version number
      run: | 
        echo """OLD_VERSION=$(cat setup.py | grep "version=" | cut -d '"' -f2 | tr -dc '0-9')""" >> $GITHUB_ENV
    - run: git checkout HEAD  # checkout current commit
    - run: |
        echo """CURRENT_VERSION=$(cat setup.py | grep "version=" | cut -d '"' -f2 | tr -dc '0-9')""" >> $GITHUB_ENV
    - name: Get numbers for   M A T H
      run: |
        echo "OLD_NUMBER=$echo$((${{env.OLD_VERSION}} - 0 ))" >> $GITHUB_ENV
        echo "CURRENT_NUMBER=$echo$((${{env.CURRENT_VERSION}} - 0 ))" >> $GITHUB_ENV
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11.x'
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        sudo apt-get install make
        pip install build setuptools wheel twine
    - name: Build the sucker
      run: |
        make build
    - uses: ncipollo/release-action@v1
      if: (( ${{ env.CURRENT_NUMBER }} > ${{ env.OLD_NUMBER }} ))
      with:
        artifacts: "dist/*"
        body: "It's releasin' time"
        generateReleaseNotes: true
        tag: ${{ env.CURRENT_VERSION }}
        commit: main
        token: ${{ secrets.GITHUB_TOKEN }}
