name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11.x'
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        sudo apt-get install make
        pip install build setuptools wheel twine
    - name: Get version number
      run: echo """CURRENT_VERSION=$(cat setup.py | grep "version=" | cut -d '"' -f2)""" >> $GITHUB_ENV
    - name: Build the sucker
      run: |
        make build
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/*"
        body: "It's releasin' time"
        generateReleaseNotes: true
        tag: ${{ env.CURRENT_VERSION }}
        commit: main
        token: ${{ secrets.GITHUB_TOKEN }}
