name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    # Start by getting the version number we originally had
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - run: git checkout HEAD^
    - name: Get version number
      run: | 
        echo """OLD_TAG=$(cat setup.py | grep "version=" | cut -d '"' -f2)""" >> $GITHUB_ENV
        echo "OLD_VERSION=$(echo ${{env.OLD_TAG}} | tr -dc '0-9')" >> $GITHUB_ENV
    - run: git checkout HEAD  # checkout current commit
    - run: |
        echo """CURRENT_TAG=$(cat setup.py | grep "version=" | cut -d '"' -f2)""" >> $GITHUB_ENV
        echo "CURRENT_VERSION=$(echo ${{env.CURRENT_TAG}} | tr -dc '0-9')" >> $GITHUB_ENV
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11.x'
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        sudo apt-get install make
        pip install build setuptools wheel twine
    - name: Build the sucker
      run: |
        make build
    - uses: ncipollo/release-action@v1
      if: (( ${{ env.CURRENT_VERSION }} > ${{ env.OLD_VERSION }} ))
      with:
        artifacts: "dist/*"
        body: "It's releasin' time"
        generateReleaseNotes: true
        tag: ${{ env.CURRENT_VERSION }}
        commit: main
        token: ${{ secrets.GITHUB_TOKEN }}
